[package]
name = "add-note-and-deps"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.49", features = ["derive"] }
env_logger = "0.11.8"
git2 = "0.20.2"
log = "0.4.28"
rusqlite = "0.37.0"
